// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChtPjR6gwof_5qSgrmaPrL8gsW5Q9q7HU',
    appId: '1:270603930893:web:c170116b28ff1f2a5af444',
    messagingSenderId: '270603930893',
    projectId: 'toluwadesign',
    authDomain: 'toluwadesign.firebaseapp.com',
    storageBucket: 'toluwadesign.appspot.com',
    measurementId: 'G-GEEP3W904S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAY_o9oWzVbvu6LJXNjeYvh7CXDj8vaJo',
    appId: '1:270603930893:android:aa19e23dc8f00c135af444',
    messagingSenderId: '270603930893',
    projectId: 'toluwadesign',
    storageBucket: 'toluwadesign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9JFc3oi8-uB7sHnotgcPXOoNwMNmGlOw',
    appId: '1:270603930893:ios:8b3c32268a95ebc35af444',
    messagingSenderId: '270603930893',
    projectId: 'toluwadesign',
    storageBucket: 'toluwadesign.appspot.com',
    iosBundleId: 'com.example.toluwaDesigns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9JFc3oi8-uB7sHnotgcPXOoNwMNmGlOw',
    appId: '1:270603930893:ios:8b3c32268a95ebc35af444',
    messagingSenderId: '270603930893',
    projectId: 'toluwadesign',
    storageBucket: 'toluwadesign.appspot.com',
    iosBundleId: 'com.example.toluwaDesigns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChtPjR6gwof_5qSgrmaPrL8gsW5Q9q7HU',
    appId: '1:270603930893:web:3596b28c3364ca8c5af444',
    messagingSenderId: '270603930893',
    projectId: 'toluwadesign',
    authDomain: 'toluwadesign.firebaseapp.com',
    storageBucket: 'toluwadesign.appspot.com',
    measurementId: 'G-QY2BRT92QH',
  );
}
